name: LiterallyIlliterate

options:
  bundleIdPrefix: com.base6a77790db3a887ec8a3521dd

targets:
  LiterallyIlliterate:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: .

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.base6a77790db3a887ec8a3521dd.app
        PRODUCT_NAME: LiterallyIlliterate
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "3.0.1"
        CURRENT_PROJECT_VERSION: "15"

    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleDisplayName: Literally Illiterate
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        ITSAppUsesNonExemptEncryption: false
